version: 2

builds:
  - id: stdinexec
    binary: stdinexec
    main: ./tools/stdinexec/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

  - id: stdinsubst
    binary: stdinsubst
    main: ./tools/stdinsubst/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

  - id: splitsec
    binary: splitsec
    main: ./tools/splitsec/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

  - id: subtract
    binary: subtract
    main: ./tools/subtract/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]

checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto
